description: "欢迎来到彩美官网，我们专注于提供高质量的音视频设备和服务。我们主营激光高清投影机、LED全彩显示屏等电子设备，致力于为您构建理想视听体验。我们还提供无线投屏系统、教学系统会议系统、家庭影院解决方案等，以及投影机维修和灯泡等配套服务。我们专业研发、销售软硬件产品，并承建网络建设和维护项目。监控设备、投影设备等其他相关产品也是我们的主营业务。欢迎您来体验！"

hb:
  # override SASS variables, please replace the dash with underline, e.g. `list-group-color` should be `list_group_color`.
  # styles:
  #   primary: '#6610f2'

  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.

  full_width: false # when true, the layout takes full width globally.

  header:
    brand: 陕西彩美电子 # the brand name, leave it empty to use site's title.
    logo_bg: "#ffffff" # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      github: sncm
      bilibili: https://space.bilibili.com/1623070437
      email: mailto:puningjun@sxcmdz.cn
      tel: 4006122568
      rss: true
  footer:
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
      _color: true # when false, remove the color of social icons.
      github: sncm
      bilibili: https://space.bilibili.com/1623070437
      email: mailto:puningjun@sxcmdz.cn
      tel: 4006122568
      rss: true
  terms:
    # the paginate for categories, tags, series list pages.
    paginate: 12
  blog:
    sidebar:
      profile:
        icon: images/profile.png
        title: 蒲宁军
        description: 销售经理及技术支持
        company: 陕西彩美
        location: 陕西
        socials:
          github: pu-007
          tel: 18602924378
          email: mailto:puningjun@sxcmdz.cn
          wechat: wechat
          tencentqq: "https://qm.qq.com/cgi-bin/qm/qr?k=MlCmF3zjHDCGvKZb5oSwac0t6kUAIzlU"
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: HB THEME # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    # post_date_format: ":date_long" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      # taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts.
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - tutorials
    giscus:
      repo: hbstack/theme
      repo_id: R_kgDOJP3qtA
      category_id: DIC_kwDOJP3qtM4CVavM
  docs:
    giscus:
      repo: hbstack/theme
      repo_id: R_kgDOJP3qtA
      category_id: DIC_kwDOJP3qtM4CVavM
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: hbstack/theme
      branch: main
      # subpath: exampleSite
  # gallery:
  #   thumbnail_size: "x640"

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: "#712cf9"
    theme_color: "#712cf9"
    short_name: "HB Theme"

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
